### ISSUE TITLE
Create dataset loader for BalitaNLP

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#12] opened 2023-11-01 15:39 UTC
Dataloader name: `balita_nlp/balita_nlp.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?balita_nlp

|     Dataset| balita_nlp |
|-------------|---|
| Description | BalitaNLP is a multimodal language dataset for image-conditional language generation and text-conditional image generation. It consists of 351,755 Filipino news articles and images gathered from Filipino news outlets. News articles are categorized into five possible groups (News, Sports, Entertainment, Crime, Other). |
| Subsets | - |
| Languages | fil |
| Tasks | Image-to-Text Generation, Text-to-Image Generation |
| License | Unknown (unknown) |
| Homepage | https://github.com/KenrickLance/BalitaNLP-Dataset |
| HF URL | - |
| Paper URL | https://storage.googleapis.com/public-kenricklancebunag/Transformer-based%20Conditional%20Language%20Models%20-%20IEOM%20Submission.pdf |

**Comment by androstj** [comment] 2023-11-02 03:01
Do you mind if I try to contribute to this PR?

**Comment by mnjkhtri** [comment] 2023-11-03 13:50
#self-assign

**Comment by sabilmakbar** [comment] 2023-12-01 05:27
Hi @mnjkhtri , may I know the current status of this dataloader creation? Feel free to discuss in here if you have any difficulties, thx!

**Comment by holylovenia** [comment] 2023-12-10 10:05
Hi @mnjkhtri, we received no response from you regarding this dataloader, so I will remove your assignment.

Anyone interested in taking this dataloader, please feel free to `#self-assign`.

**Comment by minghao-wu** [comment] 2023-12-10 16:59
#self-assign

**Comment by MJonibek** [comment] 2023-12-18 15:29
#self-assign

**Comment by MJonibek** [comment] 2024-01-04 08:42
I am removing my assignment since I am facing problem with unzipping dataset

![im](https://github.com/SEACrowd/seacrowd-datahub/assets/44943993/5f759885-e2fb-4fb8-8327-20a1af0242f0)

**Comment by sabilmakbar** [comment] 2024-01-04 19:13
Hi @MJonibek, thanks for updating the issue that you encountered. May I know the steps that you've taken leading to it (for reproducibility purpose)?

in addition, have you tried to download it via HF Dataset `dl_manager` class?
```python
from datasets import DownloadManager as dl_manager

hf_filepath = [
    "https://storage.googleapis.com/public-kenricklancebunag/BalitaNLP/2022/BalitaNLP-Dataset.zip",
    "https://storage.googleapis.com/public-kenricklancebunag/BalitaNLP/2022/BalitaNLP-images_1.zip",
    "https://storage.googleapis.com/public-kenricklancebunag/BalitaNLP/2022/BalitaNLP-images_2.zip",
    "https://storage.googleapis.com/public-kenricklancebunag/BalitaNLP/2022/BalitaNLP-images_3.zip",
    "https://storage.googleapis.com/public-kenricklancebunag/BalitaNLP/2022/BalitaNLP-images_4.zip"]
local_filepath = dl_manager().download_and_extract(hf_filepath)
```

**Comment by sabilmakbar** [comment] 2024-01-05 04:28
Hi, after trying to execute the snippets above, I'm able to download them successfully. May you try this on your end and see whether it solves the issue (hence removing your blockers and assigning this issue again)? Thanks!

**Comment by danjohnvelasco** [comment] 2024-01-05 06:56
#self-assign

**Comment by Enliven26** [comment] 2024-01-28 09:56
#self-assign

**Comment by raileymontalan** [comment] 2024-03-19 15:42
#self-assign

**Comment by raileymontalan** [comment] 2024-03-26 10:19
There are many articles in the dataset whose corresponding image file does not exist in the repository. Reporting the statistics here:
- `train` split (281403 total examples): 18923 missing images (~6.72%)
- `test` split (35177 total examples): 2356 missing images (~6.70%)
- `validation` split (35175 total examples): 2369 missing images (~6.73%)

**Comment by holylovenia** [comment] 2024-04-01 06:26
> There are many articles in the dataset whose corresponding image file does not exist in the repository. Reporting the statistics here:
> 
> * `train` split (281403 total examples): 18923 missing images (~6.72%)
> * `test` split (35177 total examples): 2356 missing images (~6.70%)
> * `validation` split (35175 total examples): 2369 missing images (~6.73%)

Could you please include this in the `_DESCRIPTION` as well? Thanks @raileymontalan!!
I will also update the datasheet to have: 262480 train examples, 32806 validation examples, and 32821 test examples.

**Comment by raileymontalan** [comment] 2024-04-01 06:34
Hi @holylovenia, so for the dataloaders, should I remove examples with no corresponding images? Or keep them as is?

**Comment by holylovenia** [comment] 2024-04-01 06:48
> Hi @holylovenia, so for the dataloaders, should I remove examples with no corresponding images? Or keep them as is?

Let's exclude them since those data instances are not useful for the `imtext` schema?

**Comment by raileymontalan** [comment] 2024-04-08 05:21
> > Hi @holylovenia, so for the dataloaders, should I remove examples with no corresponding images? Or keep them as is?
> 
> Let's exclude them since those data instances are not useful for the `imtext` schema?

Hi @holylovenia, have added this comment and remove the articles with missing images from the `imtext` schema. Ready for review, thanks!

**Closed** 2024-04-08 06:25 UTC
Labels: help wanted, bonus +1, pr-ready, top-priority
